accounts/urls.py
from django.conf.urls import url
from .views import *

app_name = "accounts"

urlpatterns = [

    url(r'^login/$', login_view, name="login"),
    
    url(r'^register/$', register_view, name="register"),
    
    url(r'^logout/$', logout_view, name="logout"),

]

blog/urls.py
from django.conf.urls import url, include # URL
from django.contrib import admin
#from django.urls import path # PATH
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [   

    url(r'^$', home_view, name='home'),

    url(r'^post/', include('post.urls')),

    url(r'^accounts/', include('accounts.urls')),

    url(r'^admin/', admin.site.urls),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import url # URL
from .views import *

# Karışıklığı önlemek için
app_name = 'post'

urlpatterns = [

    url(r'^index/$', post_index, name="index"),

    url(r'^create/$', post_create, name='create'),

    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'), # ?P argüman tanımlamak için klasik ifade. d=digit; w herhangi bir karakter

    url(r'^(?P<slug>[\w-]+)/update/$', post_update, name="update"),

    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete, name='delete'),

]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.

def home_view(request):
    #if request.user.is_authenticated():
    #    context = {
    #        'isim': 'Buğra',
    #    }
    #else:
    #    context = {
    #        'isim': 'Misafir Kullanıcı',
    #    }
    context ={
        'isim': 'Buğra',
    }
    return render(request, 'home.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} Django Dersleri {% endblock %} </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    {% include 'header.html' %}

    {% include 'messages.html' %}

    {% block body %}
        
    {% endblock %}

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/header.html
<!-- Navbar Start -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="banner">
        <div class="container">
    
             <div class="navbar-header">
    
                 <!-- Telefon ekranları için menü butonu -->
                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
    
                 <!-- İsim Soyisim veya Marka İsmi -->
                <a href="{% url 'home' %}" class="navbar-brand">Django Dersleri</a>
            </div>
    
             <nav class="collapse navbar-collapse" role="navigation">
    
                 <!-- Arama Çubuğu -->
                <form class="navbar-form navbar-left" role="search" method="GET" action="">
                    <div class="input-group">
                        <input class="form-control" type="text" name="q" placeholder="Search on blog" value="{{ request.GET.q }}">
                        <span class="input-group-btn">
                            <input class="btn btn-default" type="submit" value="Ara">
                        </span>
                    </div>
                </form>
    
                 <!-- Temel Sayfalar -->
                <ul class="nav navbar-nav navbar-right">
                    {% if request.user.is_authenticated %}
                        <li><a href="{% url 'post:create' %}">Yazı Ekle</a></li>
                    {% endif %}
                    <li><a href="{% url 'home' %}">Anasayfa</a></li>
                    <li><a href="{% url 'post:index' %}">Blog</a></li>
                    <li><a href="#">Hakkımda</a></li>
                    <li><a href="#">İletişim</a></li>

                    {% if not request.user.is_authenticated %}

                    <li> <a href="{% url 'accounts:register' %}">Üye Ol</a> </li>
                    <li> <a href="{% url 'accounts:login' %}">Giriş Yap</a> </li>
                    {% else %}
                    <li> <a href="{% url 'accounts:logout' %}">Çıkış</a> </li>
                    {% endif %}
                </ul>
    
             </nav>
    
         </div>
    </nav>

templates/home.html
{% extends 'base.html' %}

{% block title %} Anasayfa - {{ block.super }} {% endblock %}

    {% block body %}

    <div class="container">

        <div class="row">
                <div class="col-md-12">
                    <div class="jumbotron">
                        <h1>Merhaba, Dünya!</h1>
                        <p class="lead">
                            Django ile yapılmış deneme blog. Ziyaretiniz için teşekkürler.
                        </p>
                        <p>
                        <a class="btn btn-primary btn-lg" href="#" role="button">
                            Popular Post
                        </a>
                        </p>
                    </div>
                </div>
            </div><!-- /row -->

            Hoşgeldiniz, {{ request.user.get_full_name }}
    </div>

    {% endblock %}

templates/messages.html
{% if messages %}
        {% for message in messages %}
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {{ message }}
        </div>
        {% endfor %}
{% endif %}